### ISSUE TITLE
BUG: mktemp: too few X's in template 'gh-montage'

### ISSUE THREAD

**Issue by shmup** [andyfeller/gh-montage#3]
Haven't begun to debug yet, just opening the issue first

```bash
$ ./gh-montage -d hyperledger

+ getopts a:dfhm:p-: OPT
+ shift 1
+ '[' -z hyperledger ']'
+ [[ hyperledger == *\/* ]]
+ ORGANIZATION=hyperledger
+ '[' -z '' ']'
+ MONTAGEFILE=hyperledger-48.jpg
+ test -f hyperledger-48.jpg
++ mktemp -d -t gh-montage
mktemp: too few X's in template ‘gh-montage’
+ TMPDIR=
```

**Comment by andyfeller** [comment]
✨ thank you for the first issue and PR, @shmup !!!

**Comment by andyfeller** [comment]
For those curious, https://www.gnu.org/software/autogen/mktemp.html:

> Usage: mktemp [OPTION]... [TEMPLATE]
> Create a temporary file or directory, safely, and print its name.
> TEMPLATE must contain at least 3 consecutive `X's in last component.
> If TEMPLATE is not specified, use tmp.XXXXXXXXXX, and --tmpdir is implied.
> Files are created u+rw, and directories u+rwx, minus umask restrictions.
