### ISSUE TITLE
Double short opts -f

### ISSUE THREAD

**Issue by shmup** [andyfeller/gh-montage#4]
Noticed you've used `-f` twice

```
force | f)
        FORCE=true
        ;;
```

```
montage-file | f)
        MONTAGEFILE="${OPTARG}.jpg"
        ;;
```

**Comment by andyfeller** [comment]
@shmup : ugh, so embarrassing!!!  thanks for pointing this out, short flag letters are always a struggle.

The fix here is completing the rename of `montage-file` to `output-file` and use `-o` as the short opts flag.  Along with that, I'm going to bring the internal variable into alignment to minimize mental gymnastics if you're in the code. 👍

**Comment by shmup** [comment]
Hehe don't be embarrassed, my own human eyes didn't catch it, a linter's eyes did :P
